# Generated by Django 4.0.2 on 2022-02-27 01:43

import core.models
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('cod', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=60, verbose_name='User')),
                ('account', models.CharField(max_length=60, verbose_name='Account')),
                ('value', models.CharField(max_length=60, verbose_name='Value')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed')],default="pending" , max_length=20, verbose_name='Status')),
                ('way', models.CharField(choices=[('out', 'Out'), ('in', 'In')], max_length=10, verbose_name='Way')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', djongo.models.fields.EmbeddedField(model_container=core.models.Transaction)),
            ],
        ),
    ]
